"use client";

import "bootstrap/dist/css/bootstrap.min.css";
import MyNavbar from "../../components/NavBar";
// import { Inter } from "next/font/google";
import { Suspense } from "react";
import { useEffect } from "react";
import Footer from "../../components/Footer";
import { CookiesProvider } from "react-cookie";

// export const metadata = {
//   title: "BlogIT",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);
  return (
    <CookiesProvider>
      <html>
        <body>
          <MyNavbar />
          <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
          <Footer />
        </body>
      </html>
    </CookiesProvider>
  );
}
